#!/usr/bin/env bash
echo "--------"
echo "This example demonstrates how to extract Hamiltonian and overlap"
echo "matrices from a prepared HKS file into JSON-formatted file. The"
echo "HKS file bundled with this example was generated using OpenMX, see"
echo "the corresponding input file in the 'reference_input' folder."
echo "--------"
set -x
../../build/openmx-hks -vv extract-hamiltonian lead-chain.hks lead-chain.json
